spring.application.name=stockmasters

# -----------------------------
# H2 FILE DATABASE (PERSISTENT)
# -----------------------------
spring.datasource.url=jdbc:h2:file:./stockmastersdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# -----------------------------
# JPA / HIBERNATE
# -----------------------------
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# recreate schema on startup so data.sql loads correctly
spring.jpa.hibernate.ddl-auto=update

# show SQL queries in console
spring.jpa.show-sql=true

# ensures data.sql runs AFTER Hibernate creates tables
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# -----------------------------
# H2 DATABASE WEB CONSOLE
# -----------------------------
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# -----------------------------
# THYMELEAF
# -----------------------------
spring.thymeleaf.cache=false
