# -----------------------------
# MYSQL DATABASE (QA / DOCKER)
# -----------------------------
spring.datasource.url=jdbc:mysql://db:3306/stockdb
spring.datasource.username=root
spring.datasource.password=password

# -----------------------------
# JPA / HIBERNATE
# -----------------------------
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# recreate schema on startup so data.sql loads correctly
spring.jpa.hibernate.ddl-auto=update

# show SQL queries in console
spring.jpa.show-sql=true

# ensures data.sql runs AFTER Hibernate creates tables
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# -----------------------------
# THYMELEAF
# -----------------------------
spring.thymeleaf.cache=false