spring.application.name=stockmasters

# H2 in-memory database for development
spring.datasource.url=jdbc:h2:mem:stockdb

# JDBC driver
spring.datasource.driverClassName=org.h2.Driver

# default H2 credentials
spring.datasource.username=sa
spring.datasource.password=

# Hibernate configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# enable H2 web console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# show SQL queries in terminal
spring.jpa.show-sql=true

# disable Thymeleaf cache for development
spring.thymeleaf.cache=false
